# Generated by Django 4.2.4 on 2024-02-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('primary', 'primary'), ('secondary', 'secondary'), ('danger', 'danger')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Shirt', 'Shirt'), ('Outwear', 'Outwear'), ('Sport wear', 'Sport wear')], default='Shirt', max_length=20),
            preserve_default=False,
        ),
    ]
