# Generated by Django 4.2.4 on 2024-02-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_item_label_alter_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.URLField(default='http://google.com'),
            preserve_default=False,
        ),
    ]
