# Generated by Django 4.2.4 on 2024-02-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label_style',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('Eco', 'Eco')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('Eco', 'Eco')], max_length=10, null=True),
        ),
    ]
