# Generated by Django 4.2.4 on 2024-02-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_item_label_style_alter_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label_style',
            field=models.CharField(blank=True, choices=[('bg-dark', 'bg-dark'), ('bg-success', 'bg-success')], max_length=10, null=True),
        ),
    ]
