# Generated by Django 4.2.4 on 2024-02-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_item_discount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='new_price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='discount_price',
            new_name='old_price',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Test descpirtion blabla'),
            preserve_default=False,
        ),
    ]
