# Generated by Django 4.2.4 on 2024-02-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='itemorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
