# Generated by Django 4.2.11 on 2024-03-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_itemorder_ordered_itemorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
