# Generated by Django 4.2.11 on 2024-03-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_item_image_alter_item_label_alter_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Small Item', 'Small Item'), ('Medium Item', 'Medium Item'), ('Big Item', 'Big Item'), ('Very Big Item', 'Very Big Item'), ('Abstract Item', 'Abstract Item')], max_length=20, verbose_name='Type'),
        ),
    ]
