# Generated by Django 4.2.11 on 2024-03-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Big', 'Big'), ('VeryBig', 'VeryBig'), ('Abstract', 'Abstract')], max_length=20, verbose_name='Type'),
        ),
    ]
