# Generated by Django 4.2.11 on 2024-03-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_item_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
