# Generated by Django 5.0.3 on 2024-04-08 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_itemorder_total_item_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='total_item_order_amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Price must be a positive number')]),
        ),
    ]
