# Generated by Django 4.2.4 on 2024-09-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_item_stripe_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label_style',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
