# Generated by Django 4.2.11 on 2024-03-07 11:30

import OnlyShop.profiles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_appuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2, 'Your name should be minimum two characters long!'), OnlyShop.profiles.validators.name_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2, 'Your name should be minimum two characters long!'), OnlyShop.profiles.validators.name_validator]),
        ),
    ]
