# Generated by Django 4.2.11 on 2024-04-30 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_billinginfo_payment_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='payment_option',
        ),
    ]
