# Generated by Django 4.2.11 on 2024-04-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_total_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('Stripe', 'Stripe')], default='PayPal'),
            preserve_default=False,
        ),
    ]
