# Generated by Django 4.2.11 on 2024-04-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_payment_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_option',
        ),
    ]
